### PR TITLE
Fix navbar navigation

### LINKED ISSUE #16: Fix navbar hyperlinks on workshop page
If you navigate to the workshops tab, you can't navigate back to any of the other tabs since the on-click doesn't route back to the home page.

So if you're at home, and you click "about us", then:
hack.acmucsd.com -> hack.acmucsd.com/#description

But if you're in workshops, and you click "about us", then:
hack.acmucsd.com/workshops -> hack.acmucsd.com/workshops#description

which don't exist fam

### PR DESCRIPTION
**Pull request by shravanhariharan2**
frontend is my passion

Closes #16

### CODE REVIEW

**Review by garrettluu — APPROVED** [review]
I'm very glad to see you pursuing your passion! Maybe we should assign you some more frontend dev work 👀

File: src/components/Description/index.tsx [hunk 1]
```diff
@@ -1,6 +1,5 @@
 import React from 'react';
 import './style.less';
-import heart from '../../assets/heart.svg';
```
Comment (trulyronak) [inline src/components/Description/index.tsx:3]: i guess you didn't feel the love tonight :(

File: src/pages/Workshops/index.tsx [hunk 2]
```diff
@@ -9,7 +9,7 @@ const Workshops: React.FC = () => {
     <div className="page workshops">
       <Navbar />
       <div className="container workshop-content">
-        <h2>hack.py</h2>
+        <h2 id='top'>hack.py</h2>
```
Comment (trulyronak) [inline src/pages/Workshops/index.tsx]: if it works yeah go for it — otherwise the official location for `top` i'd say would be in `src/index.tsx` (change `<div className="app">` to be `<div className="app" id="top">`

**Review by trulyronak — APPROVED** [review]
we stan ♥️ our favorite frontend dev

don't do anything yucky like backend ok

File: src/pages/Workshops/index.tsx (hunk 2 above)
Comment (shravanhariharan2) [reply src/pages/Workshops/index.tsx]: `src/index.tsx` is definitely a better place to have it, I'll move it there
